version: "3.3"

services:
  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    restart: always
    env_file:
      - "env.dist"
    volumes:
      - .:/src






